/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DistributionOrder {
    id: bigint;
    tokenId: bigint;
    distributorId: bigint;
    timestamp: bigint;
    quantity: bigint;
}
export interface Batch {
    id: bigint;
    region: string;
    status: BatchStatus;
    farmName: string;
    weightKg: bigint;
    grade: string;
}
export interface Token {
    transactionHash: string;
    tokenSupply: bigint;
    timestamp: bigint;
    batchId: bigint;
}
export interface BatchLifecycle {
    distributions: Array<DistributionOrder>;
    tokens: Array<Token>;
    batch: Batch;
    redemptions: Array<Redemption>;
}
export interface Redemption {
    id: bigint;
    status: RedemptionStatus;
    redeemer: string;
    timestamp: bigint;
    quantity: bigint;
    batchId: bigint;
}
export enum BatchStatus {
    pendingVerification = "pendingVerification",
    verified = "verified",
    minted = "minted"
}
export enum RedemptionStatus {
    pending = "pending",
    completed = "completed"
}
export interface backendInterface {
    completeRedemptionRequest(id: bigint): Promise<boolean>;
    createBatch(farmName: string, region: string, weightKg: bigint, grade: string): Promise<bigint>;
    getAllBatches(): Promise<Array<Batch>>;
    getBatch(id: bigint): Promise<Batch | null>;
    getBatchInventory(batchId: bigint): Promise<bigint | null>;
    getBatchLifecycle(batchId: bigint): Promise<BatchLifecycle | null>;
    getTokenBalance(tokenId: bigint): Promise<bigint | null>;
    mintTokens(batchId: bigint, tokenSupply: bigint, transactionHash: string): Promise<boolean>;
    placeDistributionOrder(tokenId: bigint, distributorId: bigint, quantity: bigint): Promise<boolean>;
    registerDistributor(name: string, region: string, walletAddress: string): Promise<bigint>;
    submitRedemptionRequest(batchId: bigint, quantity: bigint, redeemer: string): Promise<bigint>;
    verifyBatch(id: bigint): Promise<boolean>;
}
import type { Batch as _Batch, BatchLifecycle as _BatchLifecycle, BatchStatus as _BatchStatus, DistributionOrder as _DistributionOrder, Redemption as _Redemption, RedemptionStatus as _RedemptionStatus, Token as _Token } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async completeRedemptionRequest(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completeRedemptionRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeRedemptionRequest(arg0);
            return result;
        }
    }
    async createBatch(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBatch(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBatch(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getAllBatches(): Promise<Array<Batch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBatches();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBatches();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBatch(arg0: bigint): Promise<Batch | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBatch(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBatch(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBatchInventory(arg0: bigint): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBatchInventory(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBatchInventory(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBatchLifecycle(arg0: bigint): Promise<BatchLifecycle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBatchLifecycle(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBatchLifecycle(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTokenBalance(arg0: bigint): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTokenBalance(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTokenBalance(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async mintTokens(arg0: bigint, arg1: bigint, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.mintTokens(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mintTokens(arg0, arg1, arg2);
            return result;
        }
    }
    async placeDistributionOrder(arg0: bigint, arg1: bigint, arg2: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.placeDistributionOrder(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeDistributionOrder(arg0, arg1, arg2);
            return result;
        }
    }
    async registerDistributor(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerDistributor(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerDistributor(arg0, arg1, arg2);
            return result;
        }
    }
    async submitRedemptionRequest(arg0: bigint, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRedemptionRequest(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRedemptionRequest(arg0, arg1, arg2);
            return result;
        }
    }
    async verifyBatch(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyBatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyBatch(arg0);
            return result;
        }
    }
}
function from_candid_BatchLifecycle_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BatchLifecycle): BatchLifecycle {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_BatchStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BatchStatus): BatchStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Batch_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Batch): Batch {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_RedemptionStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RedemptionStatus): RedemptionStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Redemption_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Redemption): Redemption {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Batch]): Batch | null {
    return value.length === 0 ? null : from_candid_Batch_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BatchLifecycle]): BatchLifecycle | null {
    return value.length === 0 ? null : from_candid_BatchLifecycle_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    distributions: Array<_DistributionOrder>;
    tokens: Array<_Token>;
    batch: _Batch;
    redemptions: Array<_Redemption>;
}): {
    distributions: Array<DistributionOrder>;
    tokens: Array<Token>;
    batch: Batch;
    redemptions: Array<Redemption>;
} {
    return {
        distributions: value.distributions,
        tokens: value.tokens,
        batch: from_candid_Batch_n2(_uploadFile, _downloadFile, value.batch),
        redemptions: from_candid_vec_n11(_uploadFile, _downloadFile, value.redemptions)
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _RedemptionStatus;
    redeemer: string;
    timestamp: bigint;
    quantity: bigint;
    batchId: bigint;
}): {
    id: bigint;
    status: RedemptionStatus;
    redeemer: string;
    timestamp: bigint;
    quantity: bigint;
    batchId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_RedemptionStatus_n14(_uploadFile, _downloadFile, value.status),
        redeemer: value.redeemer,
        timestamp: value.timestamp,
        quantity: value.quantity,
        batchId: value.batchId
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    region: string;
    status: _BatchStatus;
    farmName: string;
    weightKg: bigint;
    grade: string;
}): {
    id: bigint;
    region: string;
    status: BatchStatus;
    farmName: string;
    weightKg: bigint;
    grade: string;
} {
    return {
        id: value.id,
        region: value.region,
        status: from_candid_BatchStatus_n4(_uploadFile, _downloadFile, value.status),
        farmName: value.farmName,
        weightKg: value.weightKg,
        grade: value.grade
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
}): RedemptionStatus {
    return "pending" in value ? RedemptionStatus.pending : "completed" in value ? RedemptionStatus.completed : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingVerification: null;
} | {
    verified: null;
} | {
    minted: null;
}): BatchStatus {
    return "pendingVerification" in value ? BatchStatus.pendingVerification : "verified" in value ? BatchStatus.verified : "minted" in value ? BatchStatus.minted : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Batch>): Array<Batch> {
    return value.map((x)=>from_candid_Batch_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Redemption>): Array<Redemption> {
    return value.map((x)=>from_candid_Redemption_n12(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
